local v0=game:GetService("UserInputService");local v1=game:GetService("RunService");local v2=game:GetService("StarterGui");local v3=game.Players.LocalPlayer;local v4=v3.Character or v3.CharacterAdded:Wait() ;local v5=v4:WaitForChild("Humanoid");local v6=v4:WaitForChild("HumanoidRootPart");local v7=false;local v8=1330 -(226 + 1044) ;local v9=v6:FindFirstChild("FlyBodyVelocity");if v9 then v9:Destroy();end local v10=v6:FindFirstChild("FlyBodyGyro");if v10 then v10:Destroy();end local v11=Instance.new("BodyVelocity");v11.Name="FlyBodyVelocity";v11.MaxForce=Vector3.new(435440 -335440 ,100000,100117 -(32 + 85) );v11.Velocity=Vector3.new(0 + 0 ,0 + 0 ,957 -(892 + 65) );v11.Parent=v6;local v16=Instance.new("BodyGyro");v16.Name="FlyBodyGyro";v16.MaxTorque=Vector3.new(954212 -554212 ,400000,400000);v16.P=20000;v16.CFrame=v6.CFrame;v16.Parent=v6;local function v23(v25) v2:SetCore("SendNotification",{Title="Fly Script",Text=v25,Duration=6 -2 });end local function v24() local v26=0 -0 ;while true do if (v26==(351 -(87 + 263))) then if v7 then v23("Made by qrcode1 on Discord");else local v39=180 -(67 + 113) ;while true do if ((0 + 0)==v39) then v11.Velocity=Vector3.new(0,0 -0 ,0 + 0 );v16.CFrame=v6.CFrame;break;end end end break;end if (v26==(0 -0)) then v7= not v7;v5.PlatformStand=v7;v26=1;end end end v0.InputBegan:Connect(function(v27,v28) local v29=952 -(802 + 150) ;local v30;while true do if (v29==(0 -0)) then v30=0 -0 ;while true do if (v30==(0 + 0)) then if v28 then return;end if (v27.KeyCode==Enum.KeyCode.X) then v24();end break;end end break;end end end);v1.RenderStepped:Connect(function() if v7 then local v31=workspace.CurrentCamera.CFrame;local v32=Vector3.new();if v0:IsKeyDown(Enum.KeyCode.W) then v32=v32 + Vector3.new(v31.LookVector.X,997 -(915 + 82) ,v31.LookVector.Z) ;end if v0:IsKeyDown(Enum.KeyCode.S) then v32=v32-Vector3.new(v31.LookVector.X,0 -0 ,v31.LookVector.Z) ;end if v0:IsKeyDown(Enum.KeyCode.A) then v32=v32-Vector3.new(v31.RightVector.X,0 + 0 ,v31.RightVector.Z) ;end if v0:IsKeyDown(Enum.KeyCode.D) then v32=v32 + Vector3.new(v31.RightVector.X,0,v31.RightVector.Z) ;end if (v32.Magnitude>0) then v11.Velocity=v32.Unit * v8 ;else v11.Velocity=Vector3.new(0 -0 ,1187 -(1069 + 118) ,0);end v16.CFrame=workspace.CurrentCamera.CFrame;else local v35=0 -0 ;while true do if (v35==(0 -0)) then v11.Velocity=Vector3.new(0 + 0 ,0,0 -0 );v16.CFrame=v6.CFrame;break;end end end end);
-- ⚠️ WARNING: integrity protected!
--[[
 _______                        __                            __                      __        _______                                                                 __              __                                          __  __                                                __ 
/       \                      /  |                          /  |                    /  |      /       \                                                               /  |           _/  |                                        /  |/  |                                              /  |
$$$$$$$  | ______    ______   _$$ |_     ______    _______  _$$ |_     ______    ____$$ |      $$$$$$$  | __    __         ______    ______    _______   ______    ____$$ |  ______  / $$ |          ______   _______          ____$$ |$$/   _______   _______   ______    ______    ____$$ |
$$ |__$$ |/      \  /      \ / $$   |   /      \  /       |/ $$   |   /      \  /    $$ |      $$ |__$$ |/  |  /  |       /      \  /      \  /       | /      \  /    $$ | /      \ $$$$ |         /      \ /       \        /    $$ |/  | /       | /       | /      \  /      \  /    $$ |
$$    $$//$$$$$$  |/$$$$$$  |$$$$$$/   /$$$$$$  |/$$$$$$$/ $$$$$$/   /$$$$$$  |/$$$$$$$ |      $$    $$< $$ |  $$ |      /$$$$$$  |/$$$$$$  |/$$$$$$$/ /$$$$$$  |/$$$$$$$ |/$$$$$$  |  $$ |        /$$$$$$  |$$$$$$$  |      /$$$$$$$ |$$ |/$$$$$$$/ /$$$$$$$/ /$$$$$$  |/$$$$$$  |/$$$$$$$ |
$$$$$$$/ $$ |  $$/ $$ |  $$ |  $$ | __ $$    $$ |$$ |        $$ | __ $$    $$ |$$ |  $$ |      $$$$$$$  |$$ |  $$ |      $$ |  $$ |$$ |  $$/ $$ |      $$ |  $$ |$$ |  $$ |$$    $$ |  $$ |        $$ |  $$ |$$ |  $$ |      $$ |  $$ |$$ |$$      \ $$ |      $$ |  $$ |$$ |  $$/ $$ |  $$ |
$$ |     $$ |      $$ \__$$ |  $$ |/  |$$$$$$$$/ $$ \_____   $$ |/  |$$$$$$$$/ $$ \__$$ |      $$ |__$$ |$$ \__$$ |      $$ \__$$ |$$ |      $$ \_____ $$ \__$$ |$$ \__$$ |$$$$$$$$/  _$$ |_       $$ \__$$ |$$ |  $$ |      $$ \__$$ |$$ | $$$$$$  |$$ \_____ $$ \__$$ |$$ |      $$ \__$$ |
$$ |     $$ |      $$    $$/   $$  $$/ $$       |$$       |  $$  $$/ $$       |$$    $$ |      $$    $$/ $$    $$ |      $$    $$ |$$ |      $$       |$$    $$/ $$    $$ |$$       |/ $$   |      $$    $$/ $$ |  $$ |      $$    $$ |$$ |/     $$/ $$       |$$    $$/ $$ |      $$    $$ |
$$/      $$/        $$$$$$/     $$$$/   $$$$$$$/  $$$$$$$/    $$$$/   $$$$$$$/  $$$$$$$/       $$$$$$$/   $$$$$$$ |       $$$$$$$ |$$/        $$$$$$$/  $$$$$$/   $$$$$$$/  $$$$$$$/ $$$$$$/        $$$$$$/  $$/   $$/        $$$$$$$/ $$/ $$$$$$$/   $$$$$$$/  $$$$$$/  $$/        $$$$$$$/ 
                                                                                                         /  \__$$ |            $$ |                                                                                                                                                          
                                                                                                         $$    $$/             $$ |                                                                                                                                                          
                                                                                                          $$$$$$/              $$/                                                                                                                                                           

]]--
